Tagging using RAKE and spaCy
susheelk/newsegg-injection pull request #1
Opened 2021-03-18 20:59 UTC by arjun-vasudevan

2021-03-18 23:05 UTC, susheelk commented on requirements.txt
> +appdirs==1.4.4
Damn do we need all these dependencies?

2021-03-18 23:05 UTC, susheelk commented on feed_parsers/implemented_feeds.py
> +            desc_para = regex.search('(?<=<p>)(.*?)(?=<\/p>)', e.description).group(0)
nice regex lol

2021-03-18 23:55 UTC, arjun-vasudevan commented on requirements.txt
> +appdirs==1.4.4
Yep

2021-03-19 22:50 UTC, susheelk commented on pipeline/tagger.py
> +        self.pos_tag = ['PROPN', 'NOUN']
(nit) you could make this a static variable

2021-03-19 22:51 UTC, susheelk commented on pipeline/tagger.py
> +    def start(self):
You can remove this method or raise `NotImplementedError`

2021-03-19 22:55 UTC, susheelk requested changes
# +1
Resolve the comments and merge at your discretion :+1:

2021-03-29 01:31 UTC, merged